spring:
  application:
    name: laagent
langchain4j:
  ollama:
    streaming-chat-model:
      model-name: deepseek-v3.2:cloud
      base-url: http://localhost:11434
      think: false
      log-requests: true
      log-responses: true
logging:
  level:
    dev:
      langchain4j: DEBUG