# TRANSLATIONS = {
#     "category_exist": "该分类已存在",
#     "parent_point_not_exist": "父级节点不存在",
#
#     "document_category_name_exist": "文档分类名称已存在",
#     "document_category_not_exist": "文档分类不存在",
#     "document_not_exist": "文档不存在",
#     "document_chunk_not_exist": "文档分片不存在",
#     "document_id_exist": "文档序列号已存在",
#     "document_name_exist": "文档名称已存在",
#     "document_enabled": "文档已启用",
#     "document_disabled": "文档已停用",
#
#     "knowledge_category_name_exist": "知识库分类名称已存在",
#     "knowledge_category_has_child": "知识库分类有子分类，不能删除",
#     "knowledge_category_not_exist": "知识库分类不存在",
#     "knowledge_not_exist": "知识库不存在",
#     "knowledge_id_exist": "知识库编号已存在",
#     "knowledge_enabled": "知识库已启用",
#     "knowledge_disabled": "知识库已停用",
#
#     "review_preset_answer_not_empty":"直接回答时预设答案不能为空",
#     "review_not_exist":"内容审查不存在",
#
#     "tag_no_update_mark":"对话无更新的标记",
#
#     "tool_name_exist": "工具名称已存在",
#     "tool_not_exist": "工具不存在",
#     "tool_type_error": "错误的工具类型",
#
#     "category_has_child": "分类下有子节点,不能删除",
#     "category_has_agent": "分类下有未删除的智能体",
#     "category_has_document": "分类下存在文档，不能删除",
#     "category_has_knowledge": "分类下存在知识库，不能删除",
#
#     "name_exist": "名称已存在",
#     "chat_id_not_exist": "对话%(id)s不存在",
#     "chat_history_not_exist": "暂无待删除对话历史",
#     "chat_id_relevancy_agent_not_exist": "对话%(id)s关联的智能体%(agent_id)s不存在",
#
#     "upload_file_not_exist": "未检测到上传文件",
#     "upload_file_type_error": "上传文件类型错误",
#     "upload_file_not_exceed_10": "上传文件大小不超过10M"
# }
TRANSLATIONS = {
    "category_exist": "category_exist",
    "parent_point_not_exist": "parent_point_not_exist",
    "document_category_name_exist": "document_category_name_exist",
    "document_category_not_exist": "document_category_not_exist",
    "document_not_exist": "document_not_exist",
    "document_chunk_not_exist": "document_chunk_not_exist",
    "document_id_exist": "document_id_exist",
    "document_name_exist": "document_name_exist",
    "document_enabled": "document_enabled",
    "document_disabled": "document_disabled",
    "knowledge_category_name_exist": "knowledge_category_name_exist",
    "knowledge_category_has_child": "knowledge_category_has_child",
    "knowledge_category_not_exist": "knowledge_category_not_exist",
    "knowledge_not_exist": "knowledge_not_exist",
    "knowledge_id_exist": "knowledge_id_exist",
    "knowledge_enabled": "knowledge_enabled",
    "knowledge_disabled": "knowledge_disabled",
    "review_preset_answer_not_empty": "review_preset_answer_not_empty",
    "review_not_exist": "review_not_exist",
    "tag_no_update_mark": "tag_no_update_mark",
    "tool_name_exist": "tool_name_exist",
    "tool_not_exist": "tool_not_exist",
    "tool_type_error": "tool_type_error",
    "category_has_child": "category_has_child",
    "category_has_agent": "category_has_agent",
    "category_has_document": "category_has_document",
    "category_has_knowledge": "category_has_knowledge",
    "name_exist": "name_exist",
    "chat_id_not_exist": "chat_id_not_exist",
    "chat_history_not_exist": "chat_history_not_exist",
    "chat_id_relevancy_agent_not_exist": "chat_id_relevancy_agent_not_exist",
    "upload_file_not_exist": "upload_file_not_exist",
    "upload_file_type_error": "upload_file_type_error",
    "upload_file_not_exceed_10": "upload_file_not_exceed_10",
    "llm_not_exist": "llm_not_exist",
    "agent_not_exist": "agent_not_exist",
}
