LLM_NODE_CONFIG = "LLM_NODE_CONFIG"
CONDITION_NODE_CONFIG = "CONDITION_NODE_CONFIG"
KB_NODE_CONFIG = "KB_NODE_CONFIG"


# 图中变量标识符中换取环境变量的开头字符
GRAPH_ENV_START_WITH = "env"

# 变量拆分符
VARIABLE_SPLIT = "."

LOGIC_AND = "&&"
LOGIC_OR = "||"
LOGIC_AND_CONVERT = " and "
LOGIC_OR_CONVERT = " or "